DROP TABLE IF EXISTS BOOKS, AUTORS, GENRES;
CREATE TABLE BOOKS (ID INT PRIMARY KEY, BOOKNAME VARCHAR(255));
CREATE TABLE AUTORS (ID INT PRIMARY KEY, AUTORNAME VARCHAR(255));
CREATE TABLE GENRES (ID INT PRIMARY KEY, GENRENAME VARCHAR(255));